local modoptions = Spring.GetModOptions()
if modoptions.playablerapotrs ~= true and modoptions.forceallunits ~= true then return {}
else
	return {
prap_hive = {
	health		= 5000,
	autoheal	= 5,
	idletime	= 90,
	idleautoheal= 50,
	selfDestructCountdown= 0,

	-- builder builds these for free, dies in the porcess, it itself is the cost
	energycost	= 0,
	metalcost	= 450,
	buildtime	= 750,

	metalmake	= 4,
	energymake	= 25,
	energystorage= 500,

	builder		= true,
	workertime	= 200,
	buildDistance= 800,
	buildoptions = {
		"prap_hive_t2",
		"armmex",
		"armwin",
		"armsolar",
		"prap_foundling",
	},

	waterline	= 0,
	footprintx	= 6,
	footprintz	= 6,
	maxslope	= 33,
	sightdistance= 750,
	levelground	= false,
	objectname	= "praptors/hive.s3o",
	script		= "praptors/prap_hive_lus.lua",
	yardmap		= [[
	eeeeee
	eooooe
	eooooe
	eooooe
	eooooe
	eeeeee
	]],
	collisionvolumetype		= "s",
	collisionvolumeoffsets	= "0 -10 0",
	collisionvolumescales	= "96 96 96	",
	selectionVolumeType		= "s",
	selectionVolumeOffsets	= "0 -10 0",
	selectionVolumeScales	= "92 92 92	",

	capturable = false,
	category	= "RAPTOR",
	selfdestructas= "ROOST_DEATH",

	customparams= {
		iscommander = true,
		hive		= true,
		isairbase	= true,
		model_author= "FireStorm, Beherith",
		normalmaps	= "yes",
		normaltex	= "unittextures/chicken_l_normals.png",
	},
	featuredefs	= {},
	sfxtypes	= {
		explosiongenerators = {
			[1]	= "custom:blood_spray",
			[2]	= "custom:blood_explode",
			[3]	= "custom:dirt",
		},
		pieceexplosiongenerators = {
			[1]	= "blood_spray",
			[2]	= "blood_spray",
			[3]	= "blood_spray",
		},
	},
},
prap_hive_t2 = {
	health		= 10000,
	autoheal	= 10,
	idletime	= 90,
	idleautoheal= 100,
	selfDestructCountdown= 0,

	energycost	= 16000,
	metalcost	= 2800,
	buildtime	= 10500,

	metalmake	= 4,
	energymake	= 25,
	energystorage= 2000,

	builder		= true,
	workertime	= 400,
	buildDistance= 800,
	buildoptions = {
		"armmex",
		"armwin",
		"armsolar",
		"prap_foundling",
	},

	waterline	= 0,
	footprintx	= 6,
	footprintz	= 6,
	maxslope	= 33,
	sightdistance= 750,
	levelground	= false,
	objectname	= "praptors/hive.s3o",
	script		= "praptors/prap_hive_lus.lua",
	yardmap		= [[
	eeeeee
	eooooe
	eooooe
	eooooe
	eooooe
	eeeeee
	]],
	collisionvolumetype		= "s",
	collisionvolumeoffsets	= "0 -10 0",
	collisionvolumescales	= "96 96 96	",
	selectionVolumeType		= "s",
	selectionVolumeOffsets	= "0 -10 0",
	selectionVolumeScales	= "92 92 92	",

	capturable = false,
	category	= "RAPTOR",
	selfdestructas= "ROOST_DEATH",

	customparams= {
		iscommander = true,
		hive		= true,
		isairbase	= true,
		model_author= "FireStorm, Beherith",
		normalmaps	= "yes",
		normaltex	= "unittextures/chicken_l_normals.png",
	},
	featuredefs	= {},
	sfxtypes	= {
		explosiongenerators = {
			[1]	= "custom:blood_spray",
			[2]	= "custom:blood_explode",
			[3]	= "custom:dirt",
		},
		pieceexplosiongenerators = {
			[1]	= "blood_spray",
			[2]	= "blood_spray",
			[3]	= "blood_spray",
		},
	},
},
prap_pad = {
	health		= 50000,
	autoheal	= 5,
	idletime	= 90,
	idleautoheal= 50,
	energycost	= 25000,
	metalcost	= 400,
	selfDestructCountdown= 0,

	workertime	= 250,
	metalmake	= 0,
	energymake	= 0,
	energystorage= 0,

	builder = true,
	buildtime = 10500,
	buildoptions = {
		"prap_siege",
		"prap_swarm",
		"prap_nest",
	},

	waterline	= 0,
	footprintx	= 6,
	footprintz	= 6,
	sightdistance= 750,
	levelground	= false,
	objectname	= "Units/CORSY.s3o",
	script		= "praptors/prap_pad_lus.lua",
	yardmap		= [[
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	]],
	collisionvolumetype		= "s",
	collisionvolumeoffsets	= "0 -10 0",
	collisionvolumescales	= "92 92 92	",
	selectionVolumeType		= "s",
	selectionVolumeOffsets	= "0 -10 0",
	selectionVolumeScales	= "72 72 72	",

	capturable = false,
	category	= "RAPTOR",
	selfdestructas= "ROOST_DEATH",

	customparams= {
		hivepad		= true,
		isairbase	= true,
		model_author = "Mr Bob",
		normalmaps	= "yes",
		normaltex = "unittextures/cor_normal.dds",
	},
	featuredefs	= {},
	sfxtypes	= {
		explosiongenerators = {
			[1]	= "custom:blood_spray",
			[2]	= "custom:blood_explode",
			[3]	= "custom:dirt",
		},
		pieceexplosiongenerators = {
			[1]	= "blood_spray",
			[2]	= "blood_spray",
			[3]	= "blood_spray",
		},
	},
},
prap_siege = {
	buildangle = 2048,
	builder = true,
	buildpic = "CORVP.DDS",
	buildtime = 7150,
	canmove = true,
	collisionvolumeoffsets = "0 5 0",
	collisionvolumescales = "96 40 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1800,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 6,
	footprintz = 6,
	health = 3000,
	idleautoheal = 5,
	idletime = 1800,
	levelground = false,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 720,
	metalstorage = 100,
	objectname = "Units/CORVP.s3o",
	script = "Units/CORVP.lua",
	seismicsignature = 0,
	selfdestructas = "largeBuildingexplosiongenericSelfd",
	sightdistance = 279,
	terraformspeed = 500,
	workertime = 100,
	yardmap = [[
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	]],
	buildoptions = {
		[1] = "corcv",
		[2] = "cormuskrat",
		[3] = "cormlv",
		[4] = "corfav",
		[5] = "corgator",
		[6] = "corgarp",
		[7] = "corraid",
		[8] = "corlevlr",
		[9] = "corwolv",
		[10] = "cormist",
	},
	customparams = {
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 9,
		buildinggrounddecalsizey = 9,
		buildinggrounddecaltype = "decals/corvp_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -13 0",
			collisionvolumescales = "101 40 106",
			collisionvolumetype = "BOX",
			damage = 1590,
			featuredead = "HEAP",
			footprintx = 6,
			footprintz = 6,
			height = 20,
			metal = 470,
			object = "Units/corvp_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 795,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 188,
			object = "Units/cor7X7B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:WhiteLight",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "vehplantselect",
		},
	},
},
prap_swarm = {
	buildangle = 1024,
	builder = true,
	buildpic = "CORLAB.DDS",
	buildtime = 6500,
	canmove = true,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "93 92 87",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1300,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 6,
	footprintz = 6,
	health = 2900,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 620,
	metalstorage = 100,
	objectname = "Units/CORLAB.s3o",
	script = "Units/CORLAB.lua",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 290,
	terraformspeed = 500,
	workertime = 100,
	yardmap = [[
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	]],
	buildoptions = {
		[1] = "corck",
		[2] = "corak",
		[3] = "cornecro",
		[4] = "corstorm",
		[5] = "corthud",
		[6] = "corcrash",
	},
	customparams = {
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 8,
		buildinggrounddecalsizey = 8,
		buildinggrounddecaltype = "decals/corlab_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "88 28 88",
			collisionvolumetype = "Box",
			damage = 1560,
			featuredead = "HEAP",
			footprintx = 6,
			footprintz = 6,
			height = 20,
			metal = 442,
			object = "Units/corlab_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 780,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 177,
			object = "Units/cor6X6B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:WhiteLight",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "labselect",
		},
	},
},
prap_nest = {
	activatewhenbuilt = true,
	builder = true,
	buildpic = "CORAP.DDS",
	buildtime = 7180,
	canmove = true,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "128 33 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1350,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 9,
	footprintz = 6,
	health = 2150,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 840,
	metalstorage = 100,
	objectname = "Units/CORAP.s3o",
	radardistance = 510,
	radaremitheight = 40,
	script = "Units/CORAP.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingexplosiongenericSelfd",
	sightdistance = 273,
	sightemitheight = 40,
	terraformspeed = 500,
	workertime = 100,
	yardmap = "ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo",
	buildoptions = {
		[1] = "corca",
		[2] = "corfink",
		[3] = "corveng",
		[4] = "corshad",
		[5] = "corvalk",
		[6] = "corbw",
		[7] = "corhvytrans",
	},
	customparams = {
		airfactory = true,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 11,
		buildinggrounddecalsizey = 9,
		buildinggrounddecaltype = "decals/corap_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -14 -23",
			collisionvolumescales = "110 33 50",
			collisionvolumetype = "Box",
			damage = 1155,
			featuredead = "HEAP",
			footprintx = 12,
			footprintz = 9,
			height = 20,
			metal = 540,
			object = "Units/corap_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 578,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 216,
			object = "Units/cor6X6B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t1_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "airplantselect",
		},
	},
},
prap_foundling = {
	maxacc = 1,
	activatewhenbuilt = true,
	autoheal = 32,
	maxdec = 1,
	energycost = 0,
	metalcost = 450,
	builddistance = -1,
	leavetracks = true,
	buildpic = "raptors/raptorhealer.DDS",
	buildtime = 750,
	blocking = false,
	canassist = 0,
	canbuild = 1,
	canguard = 1,
	canmove = 1,
	canpatrol = 1,
	canrepair = 1,
	canreclaim = true,
	canstop = 1,
	capturable = false,
	category = "BOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE RAPTOR EMPABLE",
	collide = 0,
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "10 14 22",
	collisionvolumetype = "box",
	defaultmissiontype = "Standby",
	energymake = 3,
	explodeas = "WEAVER_DEATH",
	floater = false,
	footprintx = 1,
	footprintz = 1,
	hidedamage = 1,
	maneuverleashlength = 640,
	mass = 50,
	health = 250,
	maxslope = 18,
	speed = 75.0,
	maxwaterdepth = 0,
	metalstorage = 500,
	mobilestandorders = 1,
	movementclass = "RAPTORSMALLHOVER",
	noautofire = 0,
	objectname = "Raptors/raptorhealer1.s3o",
	reclaimspeed = 150,
	repairable = false,
	script = "Raptors/raptorhealer.cob",
	seismicsignature = 1,
	selfdestructas = "WEAVER_DEATH",
	side = "THUNDERBIRDS",
	sightdistance = 200,
	smoothanim = true,
	standingmoveorder = 1,
	stealth = 1,
	trackoffset = 1,
	trackstrength = 3,
	trackstretch = 1,
	tracktype = "RaptorTrack",
	trackwidth = 10,
	turninplace = true,
	turninplaceanglelimit = 90,
	turnrate = 1840,
	unitname = "raptor_land_swarmer_heal_t1_v1",
	upright = false,
	waterline = 12,
	workertime = 100,
	builder		= true,
	buildoptions = {
		[1] = "prap_hive",
	},
	customparams = {
		subfolder = "other/raptors",
		model_author = "KDR_11k, Beherith",
		normalmaps = "yes",
		normaltex = "unittextures/chicken_s_normals.png",
		--treeshader = "no",
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:blood_spray",
			[2] = "custom:blood_explode",
			[3] = "custom:dirt",
		},
		pieceexplosiongenerators = {
			[1] = "blood_spray",
			[2] = "blood_spray",
			[3] = "blood_spray",
		},
	},
},
} end