if Spring.GetModOptions().praptors == true or true then
	return {
		prap_nest = {
			activatewhenbuilt = true,
			autoheal = 1.8,
			builder = true,
			buildpic = "raptors/raptor_hive.DDS",
			buildtime = 725,
			capturable = false,
			canmove = true,
			category = "ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE RAPTOR EMPABLE",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "84 150 84",
			collisionvolumetype = "box",
			energycost = 1350,
			energystorage = 1000,
			explodeas = "ROOST_DEATH",
			footprintx = 12,
			footprintz = 12,
			health = 2050,
			idleautoheal = 10,
			idletime = 90,
			levelground = false,
			maxacc = 0,
			maxdec = 0,
			metalcost = 860,
			maxslope = 15,
			objectname = "Raptors/praptors/praptor_nest.s3o",
			script = "Raptors/praptors/praptor_nest_lus.lua",
			seismicsignature = 0,
			selfdestructas = "ROOST_DEATH",
			sightdistance = 510,
			smoothanim = true,
			waterline = 0,
			workertime = 300,
			yardmap = "yyyyyyyyyyyy yyyyooooyyyy yyyooooooyyy yyooooooooyy yooooooooooy yooooooooooy yooooooooooy yooooooooooy yyooooooooyy yyyooooooyyy yyyyooooyyyy yyyyyyyyyyyy",
			buildoptions = {
				[1] = "armca",
			},
			customparams = {
				subfolder = "other/raptor",
				model_author = "FireStorm, Beherith",
				normalmaps = "yes",
				normaltex = "unittextures/chicken_l_normals.png",
				upgradable = "yeet",
				--treeshader = "yes",
			},
			featuredefs = {},
			sfxtypes = {
				explosiongenerators = {
					[1] = "custom:blood_spray",
					[2] = "custom:blood_explode",
					[3] = "custom:dirt",
				},
				pieceexplosiongenerators = {
					[1] = "blood_spray",
					[2] = "blood_spray",
					[3] = "blood_spray",
				},
			},
		},
		prap_hive = {
			activatewhenbuilt = true,
			autoheal = 1.8,
			builder = true,
			buildpic = "raptors/raptor_hive.DDS",
			buildtime = 650,
			capturable = false,
			canmove = true,
			category = "ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE RAPTOR EMPABLE",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "84 150 84",
			collisionvolumetype = "box",
			energycost = 1200,
			energystorage = 1000,
			explodeas = "ROOST_DEATH",
			footprintx = 12,
			footprintz = 12,
			health = 2050,
			idleautoheal = 10,
			idletime = 90,
			levelground = false,
			maxacc = 0,
			maxdec = 0,
			metalcost = 650,
			maxslope = 15,
			objectname = "Raptors/praptors/praptor_hive.s3o",
			script = "Raptors/praptors/praptor_hive_lus.lua",
			--script = "Units/ARMLAB.cob",
			seismicsignature = 0,
			selfdestructas = "ROOST_DEATH",
			sightdistance = 510,
			smoothanim = true,
			waterline = 0,
			workertime = 300,
			yardmap = "yyyyyyyyyyyy yyyyooooyyyy yyyooooooyyy yyooooooooyy yooooooooooy yooooooooooy yooooooooooy yooooooooooy yyooooooooyy yyyooooooyyy yyyyooooyyyy yyyyyyyyyyyy",
			buildoptions = {
				[1] = "prap_nest",
			},
			customparams = {
				subfolder = "other/raptor",
				model_author = "FireStorm, Beherith",
				normalmaps = "yes",
				normaltex = "unittextures/chicken_l_normals.png",
				upgradable = "yes",
				--treeshader = "yes",
			},
			featuredefs = {},
			sfxtypes = {
				explosiongenerators = {
					[1] = "custom:blood_spray",
					[2] = "custom:blood_explode",
					[3] = "custom:dirt",
				},
				pieceexplosiongenerators = {
					[1] = "blood_spray",
					[2] = "blood_spray",
					[3] = "blood_spray",
				},
			},
		},
	}	
end