local modoptions = Spring.GetModOptions()
if modoptions.playablerapotrs ~= true and modoptions.forceallunits ~= true then return {}
else
	return {
prap_siege = {
	buildangle = 2048,
	builder = true,
	buildpic = "CORVP.DDS",
	buildtime = 7150,
	canmove = true,
	collisionvolumeoffsets = "0 5 0",
	collisionvolumescales = "96 40 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1800,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 6,
	footprintz = 6,
	health = 3000,
	idleautoheal = 5,
	idletime = 1800,
	levelground = false,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 720,
	metalstorage = 100,
	objectname = "Units/CORVP.s3o",
	script = "Units/CORVP.lua",
	seismicsignature = 0,
	selfdestructas = "largeBuildingexplosiongenericSelfd",
	sightdistance = 279,
	terraformspeed = 500,
	workertime = 100,
	yardmap = [[
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	]],
	buildoptions = {
		[1] = "corcv",
		[2] = "cormuskrat",
		[3] = "cormlv",
		[4] = "corfav",
		[5] = "corgator",
		[6] = "corgarp",
		[7] = "corraid",
		[8] = "corlevlr",
		[9] = "corwolv",
		[10] = "cormist",
	},
	customparams = {
		hive_t2 = "prap_siege_t2",
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 9,
		buildinggrounddecalsizey = 9,
		buildinggrounddecaltype = "decals/corvp_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -13 0",
			collisionvolumescales = "101 40 106",
			collisionvolumetype = "BOX",
			damage = 1590,
			featuredead = "HEAP",
			footprintx = 6,
			footprintz = 6,
			height = 20,
			metal = 470,
			object = "Units/corvp_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 795,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 188,
			object = "Units/cor7X7B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:WhiteLight",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "vehplantselect",
		},
	},
},
prap_siege_t2 = {
	buildangle = 2048,
	builder = true,
	buildpic = "CORAVP.DDS",
	buildtime = 7150,
	canmove = true,
	collisionvolumeoffsets = "0 5 0",
	collisionvolumescales = "96 40 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1800,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 6,
	footprintz = 6,
	health = 3000,
	idleautoheal = 5,
	idletime = 1800,
	levelground = false,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 720,
	metalstorage = 100,
	objectname = "Units/CORAVP.s3o",
	script = "Units/CORAVP.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingexplosiongenericSelfd",
	sightdistance = 279,
	terraformspeed = 500,
	workertime = 100,
	yardmap = [[
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	]],
	buildoptions = {
		[1] = "corcv",
		[2] = "cormuskrat",
		[3] = "cormlv",
		[4] = "corfav",
		[5] = "corgator",
		[6] = "corgarp",
		[7] = "corraid",
		[8] = "corlevlr",
		[9] = "corwolv",
		[10] = "cormist",
	},
	customparams = {
		hive_t2 = true,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 9,
		buildinggrounddecalsizey = 9,
		buildinggrounddecaltype = "decals/corvp_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -13 0",
			collisionvolumescales = "101 40 106",
			collisionvolumetype = "BOX",
			damage = 1590,
			featuredead = "HEAP",
			footprintx = 6,
			footprintz = 6,
			height = 20,
			metal = 470,
			object = "Units/corvp_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 795,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 188,
			object = "Units/cor7X7B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:WhiteLight",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "vehplantselect",
		},
	},
},
prap_swarm = {
	buildangle = 1024,
	builder = true,
	buildpic = "CORLAB.DDS",
	buildtime = 6500,
	canmove = true,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "93 92 87",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1300,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 6,
	footprintz = 6,
	health = 2900,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 620,
	metalstorage = 100,
	objectname = "Units/CORLAB.s3o",
	script = "Units/CORLAB.lua",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 290,
	terraformspeed = 500,
	workertime = 100,
	yardmap = [[
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	]],
	buildoptions = {
		[1] = "corck",
		[2] = "corak",
		[3] = "cornecro",
		[4] = "corstorm",
		[5] = "corthud",
		[6] = "corcrash",
	},
	customparams = {
		hive_t2 = "prap_swarm_t2",
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 8,
		buildinggrounddecalsizey = 8,
		buildinggrounddecaltype = "decals/corlab_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "88 28 88",
			collisionvolumetype = "Box",
			damage = 1560,
			featuredead = "HEAP",
			footprintx = 6,
			footprintz = 6,
			height = 20,
			metal = 442,
			object = "Units/corlab_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 780,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 177,
			object = "Units/cor6X6B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:WhiteLight",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "labselect",
		},
	},
},
prap_swarm_t2 = {
	buildangle = 1024,
	builder = true,
	buildpic = "CORALAB.DDS",
	buildtime = 6500,
	canmove = true,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "93 92 87",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1300,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 6,
	footprintz = 6,
	health = 2900,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 620,
	metalstorage = 100,
	objectname = "Units/CORALAB.s3o",
	script = "Units/CORALAB.lua",
	seismicsignature = 0,
	selfdestructas = "largeBuildingExplosionGenericSelfd",
	sightdistance = 290,
	terraformspeed = 500,
	workertime = 100,
	yardmap = [[
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	eeeeee
	]],
	buildoptions = {
		[1] = "corck",
		[2] = "corak",
		[3] = "cornecro",
		[4] = "corstorm",
		[5] = "corthud",
		[6] = "corcrash",
	},
	customparams = {
		hive_t2 = true,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 8,
		buildinggrounddecalsizey = 8,
		buildinggrounddecaltype = "decals/corlab_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 0 0",
			collisionvolumescales = "88 28 88",
			collisionvolumetype = "Box",
			damage = 1560,
			featuredead = "HEAP",
			footprintx = 6,
			footprintz = 6,
			height = 20,
			metal = 442,
			object = "Units/corlab_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 780,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 177,
			object = "Units/cor6X6B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:WhiteLight",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg3",
			[2] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "labselect",
		},
	},
},
prap_nest = {
	activatewhenbuilt = true,
	builder = true,
	buildpic = "CORAP.DDS",
	buildtime = 7180,
	canmove = true,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "128 33 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1350,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 9,
	footprintz = 6,
	health = 2150,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 840,
	metalstorage = 100,
	objectname = "Units/CORAP.s3o",
	radardistance = 510,
	radaremitheight = 40,
	script = "Units/CORAP.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingexplosiongenericSelfd",
	sightdistance = 273,
	sightemitheight = 40,
	terraformspeed = 500,
	workertime = 100,
	yardmap = "ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo",
	buildoptions = {
		[1] = "corca",
		[2] = "corfink",
		[3] = "corveng",
		[4] = "corshad",
		[5] = "corvalk",
		[6] = "corbw",
		[7] = "corhvytrans",
	},
	customparams = {
		hive_t2 = "prap_nest_t2",
		airfactory = true,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 11,
		buildinggrounddecalsizey = 9,
		buildinggrounddecaltype = "decals/corap_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -14 -23",
			collisionvolumescales = "110 33 50",
			collisionvolumetype = "Box",
			damage = 1155,
			featuredead = "HEAP",
			footprintx = 12,
			footprintz = 9,
			height = 20,
			metal = 540,
			object = "Units/corap_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 578,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 216,
			object = "Units/cor6X6B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t1_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "airplantselect",
		},
	},
},
prap_nest_t2 = {
	activatewhenbuilt = true,
	builder = true,
	buildpic = "CORAAP.DDS",
	buildtime = 7180,
	canmove = true,
	collisionvolumeoffsets = "0 0 0",
	collisionvolumescales = "128 33 96",
	collisionvolumetype = "Box",
	corpse = "DEAD",
	energycost = 1350,
	energystorage = 100,
	explodeas = "largeBuildingexplosiongeneric",
	footprintx = 9,
	footprintz = 6,
	health = 2150,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 15,
	maxwaterdepth = 0,
	metalcost = 840,
	metalstorage = 100,
	objectname = "Units/CORAAP.s3o",
	radardistance = 510,
	radaremitheight = 40,
	script = "Units/CORAAP.cob",
	seismicsignature = 0,
	selfdestructas = "largeBuildingexplosiongenericSelfd",
	sightdistance = 273,
	sightemitheight = 40,
	terraformspeed = 500,
	workertime = 100,
	yardmap = "ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo",
	buildoptions = {
		[1] = "corca",
		[2] = "corfink",
		[3] = "corveng",
		[4] = "corshad",
		[5] = "corvalk",
		[6] = "corbw",
		[7] = "corhvytrans",
	},
	customparams = {
		hive_t2 = true,
		airfactory = true,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 11,
		buildinggrounddecalsizey = 9,
		buildinggrounddecaltype = "decals/corap_aoplane.dds",
		model_author = "Mr Bob",
		normaltex = "unittextures/cor_normal.dds",
		subfolder = "CorBuildings/LandFactories",
		unitgroup = "builder",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -14 -23",
			collisionvolumescales = "110 33 50",
			collisionvolumetype = "Box",
			damage = 1155,
			featuredead = "HEAP",
			footprintx = 12,
			footprintz = 9,
			height = 20,
			metal = 540,
			object = "Units/corap_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 578,
			footprintx = 6,
			footprintz = 6,
			height = 4,
			metal = 216,
			object = "Units/cor6X6B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:radarpulse_t1_slow",
		},
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		unitcomplete = "unitready",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "airplantselect",
		},
	},
},
prap_foundling = {
	maxacc = 1,
	activatewhenbuilt = true,
	autoheal = 32,
	maxdec = 1,
	energycost = 0,
	metalcost = 450,
	builddistance = -1,
	leavetracks = true,
	buildpic = "raptors/raptorhealer.DDS",
	buildtime = 750,
	blocking = false,
	canassist = 0,
	canbuild = 1,
	canguard = 1,
	canmove = 1,
	canpatrol = 1,
	canrepair = 1,
	canreclaim = true,
	canstop = 1,
	capturable = false,
	category = "BOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE RAPTOR EMPABLE",
	collide = 0,
	collisionvolumeoffsets = "0 -1 0",
	collisionvolumescales = "10 14 22",
	collisionvolumetype = "box",
	defaultmissiontype = "Standby",
	energymake = 3,
	explodeas = "WEAVER_DEATH",
	floater = false,
	footprintx = 1,
	footprintz = 1,
	hidedamage = 1,
	maneuverleashlength = 640,
	mass = 50,
	health = 250,
	maxslope = 18,
	speed = 75.0,
	maxwaterdepth = 0,
	metalstorage = 500,
	mobilestandorders = 1,
	movementclass = "RAPTORSMALLHOVER",
	noautofire = 0,
	objectname = "Raptors/raptorhealer1.s3o",
	reclaimspeed = 150,
	repairable = false,
	script = "Raptors/raptorhealer.cob",
	seismicsignature = 1,
	selfdestructas = "WEAVER_DEATH",
	side = "THUNDERBIRDS",
	sightdistance = 200,
	smoothanim = true,
	standingmoveorder = 1,
	stealth = 1,
	trackoffset = 1,
	trackstrength = 3,
	trackstretch = 1,
	tracktype = "RaptorTrack",
	trackwidth = 10,
	turninplace = true,
	turninplaceanglelimit = 90,
	turnrate = 1840,
	unitname = "raptor_land_swarmer_heal_t1_v1",
	upright = false,
	waterline = 12,
	workertime = 100,
	builder		= true,
	buildoptions = {
		[1] = "prap_hive",
	},
	customparams = {
		subfolder = "other/raptors",
		model_author = "KDR_11k, Beherith",
		normalmaps = "yes",
		normaltex = "unittextures/chicken_s_normals.png",
		--treeshader = "no",
	},
	sfxtypes = {
		explosiongenerators = {
			[1] = "custom:blood_spray",
			[2] = "custom:blood_explode",
			[3] = "custom:dirt",
		},
		pieceexplosiongenerators = {
			[1] = "blood_spray",
			[2] = "blood_spray",
			[3] = "blood_spray",
		},
	},
},
prap_mex = {
	activatewhenbuilt = true,
	buildangle = 8192,
	buildingmask = 0,
	buildpic = "ARMMEX.DDS",
	buildtime = 1800,
	canrepeat = false,
	category = "CANBEUW",
	collisionvolumeoffsets = "0 -2 0",
	collisionvolumescales = "48 33 48",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energycost = 500,
	energyupkeep = 3,
	explodeas = "smallBuildingExplosionGeneric",
	extractsmetal = 0.001,
	footprintx = 4,
	footprintz = 4,
	health = 189,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 30,
	metalcost = 50,
	metalstorage = 50,
	objectname = "Units/ARMMEX.s3o",
	onoffable = true,
	script = "Units/ARMMEX.cob",
	seismicsignature = 0,
	selfdestructas = "smallMex",
	selfdestructcountdown = 1,
	sightdistance = 273,
	yardmap = "h cbbbbbbc bsossbsb bbsbbsob bsbbbbsb bsbbbbsb bosbbsbb bsbssosb cbbbbbbc",
	customparams = {
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 5,
		buildinggrounddecalsizey = 5,
		buildinggrounddecaltype = "decals/armmex_aoplane.dds",
		cvbuildable = true,
		metal_extractor = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "ArmBuildings/LandEconomy",
		unitgroup = "metal",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.510162353516 -0.044793737793 0.21223449707",
			collisionvolumescales = "52.280090332 25.2522125244 52.9224243164",
			collisionvolumetype = "Box",
			damage = 102,
			featuredead = "HEAP",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			metal = 33,
			object = "Units/armmex_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 51,
			footprintx = 3,
			footprintz = 3,
			height = 4,
			metal = 13,
			object = "Units/arm3X3B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		activate = "mexon",
		canceldestruct = "cancel2",
		deactivate = "mexoff",
		underattack = "warning1",
		working = "mexworking",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "mexselect",
		},
	},
},
prap_win = {
	activatewhenbuilt = true,
	buildpic = "ARMWIN.DDS",
	buildtime = 1600,
	canrepeat = false,
	collisionvolumeoffsets = "0 1 0",
	collisionvolumescales = "34 87 34",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energycost = 175,
	energystorage = 0.5,
	explodeas = "windboom",
	footprintx = 3,
	footprintz = 3,
	health = 196,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 10,
	maxwaterdepth = 0,
	metalcost = 37,
	objectname = "Units/ARMWIN.s3o",
	script = "Units/ARMWIN.cob",
	seismicsignature = 0,
	selfdestructas = "windboom",
	sightdistance = 273,
	windgenerator = 25,
	yardmap = "ooo ooo ooo",
	customparams = {
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 5,
		buildinggrounddecalsizey = 5,
		buildinggrounddecaltype = "decals/armwin_aoplane.dds",
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "ArmBuildings/LandEconomy",
		unitgroup = "energy",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.407234191895 -7.26560776367 -4.28938293457",
			collisionvolumescales = "41.3442230225 45.3115844727 37.0443725586",
			collisionvolumetype = "Box",
			damage = 106,
			featuredead = "HEAP",
			footprintx = 3,
			footprintz = 3,
			height = 40,
			metal = 23,
			object = "Units/armwin_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 53,
			footprintx = 3,
			footprintz = 3,
			height = 4,
			metal = 9,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "windgen",
		},
	},
},
prap_solar = {
	activatewhenbuilt = true,
	buildangle = 4000,
	buildpic = "ARMSOLAR.DDS",
	buildtime = 2800,
	canrepeat = false,
	collisionvolumeoffsets = "0.0 -18.0 1.0",
	collisionvolumescales = "50.0 76.0 50.0",
	collisionvolumetype = "Ell",
	corpse = "DEAD",
	damagemodifier = 0.5,
	energycost = 0,
	energystorage = 50,
	-- negative energyupkeep means it's conditional so when unit is off won't produce
	energyupkeep = -20,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 5,
	footprintz = 5,
	health = 340,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 10,
	maxwaterdepth = 0,
	metalcost = 155,
	objectname = "Units/ARMSOLAR.s3o",
	onoffable = true,
	script = "Units/ARMSOLAR.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "yyoyy yoooy ooooo yoooy yyoyy",
	customparams = {
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 8,
		buildinggrounddecalsizey = 8,
		buildinggrounddecaltype = "decals/armsolar_aoplane.dds",
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		solar = true,
		subfolder = "ArmBuildings/LandEconomy",
		unitgroup = "energy",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -18 1",
			collisionvolumescales = "50 76 50",
			collisionvolumetype = "Ell",
			damage = 184,
			featuredead = "HEAP",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			metal = 75,
			object = "Units/armsolar_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 92,
			footprintx = 5,
			footprintz = 5,
			height = 4,
			metal = 30,
			object = "Units/arm5X5B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-solar-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-solar-deactivate",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "solar1",
		},
	},
},
prap_mex_t2 = {
	activatewhenbuilt = true,
	buildangle = 8192,
	buildingmask = 0,
	buildpic = "ARMMEX.DDS",
	buildtime = 1800,
	canrepeat = false,
	category = "CANBEUW",
	collisionvolumeoffsets = "0 -2 0",
	collisionvolumescales = "48 33 48",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energycost = 500,
	energyupkeep = 3,
	explodeas = "smallBuildingExplosionGeneric",
	extractsmetal = 0.004,
	footprintx = 4,
	footprintz = 4,
	health = 189,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 30,
	metalcost = 50,
	metalstorage = 50,
	objectname = "Units/ARMMOHO.s3o",
	onoffable = true,
	script = "Units/ARMMOHO.cob",
	seismicsignature = 0,
	selfdestructas = "smallMex",
	selfdestructcountdown = 1,
	sightdistance = 273,
	yardmap = "h cbbbbbbc bsossbsb bbsbbsob bsbbbbsb bsbbbbsb bosbbsbb bsbssosb cbbbbbbc",
	customparams = {
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 5,
		buildinggrounddecalsizey = 5,
		buildinggrounddecaltype = "decals/armmex_aoplane.dds",
		cvbuildable = true,
		metal_extractor = 1,
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "ArmBuildings/LandEconomy",
		unitgroup = "metal",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.510162353516 -0.044793737793 0.21223449707",
			collisionvolumescales = "52.280090332 25.2522125244 52.9224243164",
			collisionvolumetype = "Box",
			damage = 102,
			featuredead = "HEAP",
			footprintx = 3,
			footprintz = 3,
			height = 20,
			metal = 33,
			object = "Units/armmex_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "55.0 4.0 6.0",
			collisionvolumetype = "cylY",
			damage = 51,
			footprintx = 3,
			footprintz = 3,
			height = 4,
			metal = 13,
			object = "Units/arm3X3B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
		},
	},
	sounds = {
		activate = "mexon",
		canceldestruct = "cancel2",
		deactivate = "mexoff",
		underattack = "warning1",
		working = "mexworking",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "mexselect",
		},
	},
},
prap_win_t2 = {
	activatewhenbuilt = true,
	buildpic = "ARMWIN.DDS",
	buildtime = 1600,
	canrepeat = false,
	collisionvolumeoffsets = "0 1 0",
	collisionvolumescales = "34 87 34",
	collisionvolumetype = "CylY",
	corpse = "DEAD",
	energycost = 175,
	energystorage = 0.5,
	explodeas = "windboom",
	footprintx = 3,
	footprintz = 3,
	health = 196,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 10,
	maxwaterdepth = 0,
	metalcost = 37,
	objectname = "Units/scavbuildings/ARMWINT2.s3o",
	script = "Units/scavbuildings/ARMWINT2.cob",
	seismicsignature = 0,
	selfdestructas = "windboom",
	sightdistance = 273,
	windgenerator = 100,
	yardmap = "ooo ooo ooo",
	customparams = {
		energymultiplier = 4,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 5,
		buildinggrounddecalsizey = 5,
		buildinggrounddecaltype = "decals/armwin_aoplane.dds",
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		subfolder = "ArmBuildings/LandEconomy",
		unitgroup = "energy",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0.407234191895 -7.26560776367 -4.28938293457",
			collisionvolumescales = "41.3442230225 45.3115844727 37.0443725586",
			collisionvolumetype = "Box",
			damage = 106,
			featuredead = "HEAP",
			footprintx = 3,
			footprintz = 3,
			height = 40,
			metal = 23,
			object = "Units/armwin_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			collisionvolumescales = "85.0 14.0 6.0",
			collisionvolumetype = "cylY",
			damage = 53,
			footprintx = 3,
			footprintz = 3,
			height = 4,
			metal = 9,
			object = "Units/arm4X4A.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		canceldestruct = "cancel2",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "windgen",
		},
	},
},
prap_solar_t2 = {
	activatewhenbuilt = true,
	buildangle = 4000,
	buildpic = "ARMSOLAR.DDS",
	buildtime = 2800,
	canrepeat = false,
	collisionvolumeoffsets = "0.0 -18.0 1.0",
	collisionvolumescales = "50.0 76.0 50.0",
	collisionvolumetype = "Ell",
	corpse = "DEAD",
	damagemodifier = 0.5,
	energycost = 0,
	energystorage = 50,
	-- negative energyupkeep means it's conditional so when unit is off won't produce
	energyupkeep = -80,
	explodeas = "smallBuildingexplosiongeneric",
	footprintx = 5,
	footprintz = 5,
	health = 340,
	idleautoheal = 5,
	idletime = 1800,
	maxacc = 0,
	maxdec = 0,
	maxslope = 10,
	maxwaterdepth = 0,
	metalcost = 155,
	objectname = "Units/CORADVSOL.s3o",
	onoffable = true,
	script = "Units/CORADVSOL.cob",
	seismicsignature = 0,
	selfdestructas = "smallBuildingExplosionGenericSelfd",
	sightdistance = 273,
	yardmap = "yyoyy yoooy ooooo yoooy yyoyy",
	customparams = {
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 8,
		buildinggrounddecalsizey = 8,
		buildinggrounddecaltype = "decals/armsolar_aoplane.dds",
		model_author = "Cremuss",
		normaltex = "unittextures/Arm_normal.dds",
		removestop = true,
		removewait = true,
		solar = true,
		subfolder = "ArmBuildings/LandEconomy",
		unitgroup = "energy",
		usebuildinggrounddecal = true,
	},
	featuredefs = {
		dead = {
			blocking = true,
			category = "corpses",
			collisionvolumeoffsets = "0 -18 1",
			collisionvolumescales = "50 76 50",
			collisionvolumetype = "Ell",
			damage = 184,
			featuredead = "HEAP",
			footprintx = 5,
			footprintz = 5,
			height = 20,
			metal = 75,
			object = "Units/armsolar_dead.s3o",
			reclaimable = true,
		},
		heap = {
			blocking = false,
			category = "heaps",
			damage = 92,
			footprintx = 5,
			footprintz = 5,
			height = 4,
			metal = 30,
			object = "Units/arm5X5B.s3o",
			reclaimable = true,
			resurrectable = 0,
		},
	},
	sfxtypes = {
		pieceexplosiongenerators = {
			[1] = "deathceg2",
			[2] = "deathceg3",
			[3] = "deathceg4",
		},
	},
	sounds = {
		activate = "arm-bld-solar-activate",
		canceldestruct = "cancel2",
		deactivate = "arm-bld-solar-deactivate",
		underattack = "warning1",
		count = {
			[1] = "count6",
			[2] = "count5",
			[3] = "count4",
			[4] = "count3",
			[5] = "count2",
			[6] = "count1",
		},
		select = {
			[1] = "solar1",
		},
	},
},
} end