return {
	mobile_lab_public = {
		builddistance = 130,
		builder = true,
		buildpic = "ARMCK.DDS",
		buildtime = 3450,
		canmove = true,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "27 30 27",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 1600,
		energymake = 7,
		energystorage = 50,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 2,
		footprintz = 2,
		health = 600,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.552,
		maxdec = 3.45,
		maxslope = 20,
		maxwaterdepth = 25,
		metalcost = 110,
		movementclass = "BOT3",
		objectname = "Units/ARMCK.s3o",
		script = "Units/ARMCK.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 305,
		speed = 36,
		terraformspeed = 450,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.792,
		turnrate = 1265,
		upright = true,
		workertime = 80,
		buildoptions = {
			[1] = "armpw",
		},
		customparams = {
			model_author = "Kaiser",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots",
			unitgroup = "builder",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "1.68473052979 1.77978515623e-05 -1.12860870361",
				collisionvolumescales = "28.1473846436 25.0852355957 27.3032073975",
				collisionvolumetype = "Box",
				damage = 424,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 40,
				metal = 66,
				object = "Units/armck_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 262,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 26,
				object = "Units/arm2X2D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg3-builder",
				[2] = "deathceg2-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
	},
	mobile_lab_hidden = {
		buildangle = 1024,
		builder = true,
		buildpic = "ARMLAB.DDS",
		buildtime = 6500,
		canmove = true,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "84 22 84",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 1200,
		energystorage = 100,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 6,
		footprintz = 6,
		health = 2900,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 15,
		maxwaterdepth = 0,
		metalcost = 650,
		metalstorage = 100,
		objectname = "Units/ARMLAB.s3o",
		script = "mobile_lab_hidden_lus.lua",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 290,
		terraformspeed = 500,
		workertime = 100,
		yardmap = "ooooooooooooooooooeeeeeeeeeeeeeeeeee",
		buildoptions = {
			[1] = "armpw",
		},
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 9,
			buildinggrounddecalsizey = 9,
			buildinggrounddecaltype = "decals/armlab_aoplane.dds",
			model_author = "Cremuss",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBuildings/LandFactories",
			unitgroup = "builder",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -7 0",
				collisionvolumescales = "95 22 95",
				collisionvolumetype = "Box",
				damage = 1614,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 6,
				height = 40,
				metal = 458,
				object = "Units/armlab_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 807,
				footprintx = 5,
				footprintz = 5,
				height = 4,
				metal = 183,
				object = "Units/arm5X5B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "unitready",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "labselect",
			},
		},
	},
}